services:
  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: supertokens
    ports:
      - 5432:5432
    networks:
      - intranet
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U postgresuser -d supertokens
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    depends_on:
      - db
    ports:
      - "3567:3567"
    networks:
      - intranet
    restart: unless-stopped
    environment:
      API_KEYS: ${SUPERTOKENS_API_KEYS}
      POSTGRESQL_CONNECTION_URI: postgresql://postgresuser:postgrespass@db:5432/supertokens
    healthcheck:
      test: curl -f http://localhost:3567/hello | grep Hello
networks:
  intranet:
volumes:
  db_data:
