services:
  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    ports:
      - "3567:3567"
    restart: unless-stopped
    healthcheck:
      test: "curl -f http://localhost:3567/hello"
      start_period: 10s
