enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@better-auth/cli@*":
    dependencies:
      "@babel/core": latest
  "better-auth@*":
    dependencies:
      drizzle-orm: latest
  "drizzle-kit@*":
    dependencies:
      "drizzle-orm": "*"
