services:
  redis:
    image: redis:8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - intranet
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
  postgres:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sparrow
      POSTGRES_PASSWORD: flyhigh
      POSTGRES_MULTIPLE_DATABASES: sparrow_auth,sparrow_posts
    volumes:
      - postgres_data:/var/lib/postgres/data
      - ./docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    networks:
      - intranet
    healthcheck:
      test: pg_isready -U sparrow
      interval: 5s
      timeout: 5s
  nats:
    image: nats:2-alpine
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    command: "-js -sd /data -m 8222"
    volumes:
      - nats_data:/data
    networks:
      - intranet
    healthcheck:
      test: wget -qO- http://localhost:8222/healthz
      timeout: 1s
      interval: 3s

volumes:
  redis_data:
  postgres_data:
  nats_data:

networks:
  intranet:
